# Generated by Django 5.2.7 on 2025-10-08 16:41

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('subtitle', models.CharField(max_length=255, verbose_name='عنوان تخصص')),
                ('description', models.TextField(verbose_name='توضیح خلاصه')),
                ('image_name', models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بخش اصلی صفحه',
                'verbose_name_plural': 'بخش های اصلی صفحه',
            },
        ),
    ]
