# Generated by Django 5.2.7 on 2025-10-08 17:16

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image_name', models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بخش درباره من',
                'verbose_name_plural': 'بخش های درباره من',
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
