# Generated by Django 5.2.7 on 2025-10-08 17:27

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutsection_alter_herosection_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
