# Generated by Django 5.2.7 on 2025-10-08 17:35

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutsection_resume_alter_aboutsection_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تایتل')),
                ('proficiency', models.PositiveIntegerField(help_text='مقدار بین 0 تا 100', verbose_name='درصد تسلط')),
            ],
            options={
                'verbose_name': 'بخش مهارت من',
                'verbose_name_plural': 'بخش مهارت های من',
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
