# Generated by Django 5.2.7 on 2025-10-08 18:09

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experiencesection_alter_aboutsection_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image_name', models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بخش خدمات من',
                'verbose_name_plural': 'بخش های خدمات من',
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
