# Generated by Django 5.2.7 on 2025-10-08 18:15

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicesection_alter_aboutsection_image_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name': 'بخش خدمات من', 'verbose_name_plural': 'بخش خدمات های من'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
