# Generated by Django 5.2.7 on 2025-10-08 18:42

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_aboutsection_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('text', models.TextField(verbose_name='متن')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
