# Generated by Django 5.2.7 on 2025-10-09 14:21

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_projects_alter_aboutsection_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image_name',
            field=models.ImageField(upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='summery_description',
            field=models.TextField(verbose_name='خلاصه توضیحات'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.TextField(verbose_name='فناوری ها'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='تصویر'),
        ),
    ]
